import "./globals.css";

import { Inter, Geist, Poppins } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${geistSans.className} ${poppins.className}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
